<?php

/**
 * @file
 * Provides a CPF Field Type and a CPF Form Element for storing CPF number data.
 */

/**
 * Implments hook_libraries_info().
 */
function cpf_libraries_info() {
  $libraries['mask_plugin'] = [
    'name' => 'jQuery Mask Plugin',
    'vendor url' => 'https://igorescobar.github.io/jQuery-Mask-Plugin/',
    'download url' => 'https://github.com/igorescobar/jQuery-Mask-Plugin',
    'version arguments' => [
      'file' => 'jquery.mask.min.js',
      // e.g. jQuery Mask Plugin v1.14.10.
      'pattern' => '/jQuery Mask Plugin v(\d+\.+\d+(\.+\d+)?)/',
      'lines' => 3,
    ],
    'files' => [
      'js' => ['jquery.mask.min.js'],
    ],
  ];

  return $libraries;
}

/**
 * Implements hook_library_info_alter().
 */
function cpf_library_info_alter(&$libraries, $extension) {
  if ($extension == 'cpf' and isset($libraries['mask_plugin'])) {
    $library_path = libraries_get_path('mask_plugin');
    if (strpos($library_path, '/') !== 0) {
      $library_path = '/' . $library_path;
    }

    // Set the correct path to where the library was downloaded.
    $libraries['mask_plugin']['js'][$library_path . '/jquery.mask.min.js'] = $libraries['mask_plugin']['js']['jquery.mask.min.js'];
    unset($libraries['mask_plugin']['js']['jquery.mask.min.js']);
  }
}

/**
 * Implments hook_requirements().
 */
function cpf_requirements($phase) {
   $requirements = [];

  // Check to see if the jQuery Mask Plugin library is available.
  if ($phase == 'runtime') {
    $library = libraries_detect('mask_plugin');

    if ($library && !empty($library['installed'])) {
      if ($library['version']) {
        $description = t('Version %i installed', ['%i' => $library['version']]);
      }
      else {
        $description = t('Unable to detect version.');
      }

      $requirements['mask_plugin'] = [
        'title' => t('jQuery Mask Plugin'),
        'description' => $description,
        'severity' => REQUIREMENT_OK,
      ];
    }
    else {
      $requirements['mask_plugin'] = [
        'title' => t('jQuery Mask Plugin'),
        'description' => t('jQuery Mask Plugin library not found. Please consult the README.md for installation instructions.'),
        'severity' => REQUIREMENT_ERROR,
      ];
    }
  }

  return $requirements;
}
